name: lint-datapack
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Dependency
        uses: actions/checkout@v3
        with:
          repository: ProjectTSB/TheSkyBlessing
          path: TSB-master
          fetch-depth: 0
          sparse-checkout: |
            NaturalMergeSort
            OhMyDat
            ScoreToHealth

      - run: |
          mv -f TSB-master/** ../TSB-Patcher

      - name: Test
        uses: ChenCMD/datapack-linter@v1
        with:
          outputDefine: public
          notOutputSuccess: true