name: lint-datapack
on:
    push:
    pull_request:
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: true
jobs:
    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
          - name: Generate Token
            id: generate_token
            uses: tibdex/github-app-token@v1
            with:
                app_id: ${{ secrets.UPDATER_ID }}
                private_key: ${{ secrets.UPDATER_KEY }}

          - name: Checkout Repository
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Datapack Linter
            uses: ChenCMD/datapack-linter@v2
            with:
                GITHUB_TOKEN: ${{ github.token }}
                muteSuccessResult: true
                ignoreLintPathPattern: |
                    animated_java:**

          - name: Checkout Asset
            if: ${{ github.ref == 'refs/heads/master' }}
            uses: actions/checkout@v4
            with:
                repository: haiiro2gou/TSB-Asset
                ref: patcher/master
                path: ./Asset2
                fetch-depth: 0
                persist-credentials: false

          - name: Setup minimum typescript code runner
            if: ${{ github.ref == 'refs/heads/master'}}
            run: |
                npm i -g ts-node
                npm i -D @types/node

          - name: Generate declares.d.mcfunction
            if: ${{ github.ref == 'refs/heads/master' }}
            run: |
                ts-node ./.github/workflows/make-declares-mcf.ts
            env:
                CHECKOUT_PATH: /home/runner/work/TheSkyBlessing/TheSkyBlessing/
                REPOSITORY: haiiro2gou/TSB-Patcher
                BRANCH: master
                VISIBILITY_FILTER: |
                    function@asset:artifact/artifact_name/trigger/2.check_condition
                    function@asset:artifact/artifact_name/trigger/3.main
                    function@asset:artifact/artifact_name/give/2.give
                    function@asset:effect/effect_name/register
                    function@asset:effect/effect_name/given/
                    function@asset:effect/effect_name/tick/
                    function@asset:effect/effect_name/re-given/
                    function@asset:effect/effect_name/remove/
                    function@asset:effect/effect_name/end/
                    function@asset:island/island_id/register/register
                    function@asset:mob/mob_name/summon/2.summon
                    function@asset:mob/mob_name/register
                    function@asset:mob/mob_name/attack/
                    function@asset:mob/mob_name/death/
                    function@asset:mob/mob_name/hurt/
                    function@asset:mob/mob_name/tick/
                    function@asset:mob/mob_name/attack/SOMETHING_FUNCTION
                    function@asset:mob/mob_name/death/SOMETHING_FUNCTION
                    function@asset:mob/mob_name/hurt/SOMETHING_FUNCTION
                    function@asset:spawner/spawner_id/register
                    function@asset:teleporter/tp_id/register
                    function@asset:trader/trader_name/register/register
                OUTPUT_PATH: ./Asset2/Asset/data/minecraft/functions/declares.d.mcfunction
                OUTPUT_RESOURCE_PATH: minecraft:declares.d

          - name: Deploy declares to Asset Repository
            if: ${{ github.ref == 'refs/heads/master' }}
            uses: actions-js/push@v1.4
            with:
                github_token: ${{ steps.generate_token.outputs.token }}
                repository: haiiro2gou/TSB-Asset
                branch: patcher/master
                directory: ./Asset2
                message: |
                    Update Declares from haiiro2gou/TSB-Patcher@${{ github.SHA }}

                    [regenerate cache]