name: lint-datapack
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: TSB-Patcher

      - name: Checkout Dependency
        uses: actions/checkout@v3
        with:
          repository: ProjectTSB/TheSkyBlessing
          fetch-depth: 0
      - run: git checkout refs/tags/v0.1.6

      - name: Test
        uses: ChenCMD/datapack-linter@v1
        with:
          outputDefine: public
          notOutputSuccess: true
